/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PrintsRouteImport } from './routes/prints'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as NegativesRouteImport } from './routes/negatives'
import { Route as EditionsRouteImport } from './routes/editions'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as SettingsManufacturersRouteImport } from './routes/settings.manufacturers'
import { Route as SettingsFilmStocksRouteImport } from './routes/settings.film-stocks'
import { Route as SettingsCustomerTypesRouteImport } from './routes/settings.customer-types'
import { Route as CustomersIdRouteImport } from './routes/customers.$id'
import { Route as CustomersIdIndexRouteImport } from './routes/customers.$id.index'
import { Route as CustomersIdOrdersRouteImport } from './routes/customers.$id.orders'
import { Route as CustomersIdNotesRouteImport } from './routes/customers.$id.notes'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintsRoute = PrintsRouteImport.update({
  id: '/prints',
  path: '/prints',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const NegativesRoute = NegativesRouteImport.update({
  id: '/negatives',
  path: '/negatives',
  getParentRoute: () => rootRouteImport,
} as any)
const EditionsRoute = EditionsRouteImport.update({
  id: '/editions',
  path: '/editions',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomersRoute,
} as any)
const SettingsManufacturersRoute = SettingsManufacturersRouteImport.update({
  id: '/manufacturers',
  path: '/manufacturers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsFilmStocksRoute = SettingsFilmStocksRouteImport.update({
  id: '/film-stocks',
  path: '/film-stocks',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCustomerTypesRoute = SettingsCustomerTypesRouteImport.update({
  id: '/customer-types',
  path: '/customer-types',
  getParentRoute: () => SettingsRoute,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CustomersRoute,
} as any)
const CustomersIdIndexRoute = CustomersIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomersIdRoute,
} as any)
const CustomersIdOrdersRoute = CustomersIdOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => CustomersIdRoute,
} as any)
const CustomersIdNotesRoute = CustomersIdNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => CustomersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRouteWithChildren
  '/editions': typeof EditionsRoute
  '/negatives': typeof NegativesRoute
  '/orders': typeof OrdersRoute
  '/prints': typeof PrintsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/customers/$id': typeof CustomersIdRouteWithChildren
  '/settings/customer-types': typeof SettingsCustomerTypesRoute
  '/settings/film-stocks': typeof SettingsFilmStocksRoute
  '/settings/manufacturers': typeof SettingsManufacturersRoute
  '/customers/': typeof CustomersIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/customers/$id/notes': typeof CustomersIdNotesRoute
  '/customers/$id/orders': typeof CustomersIdOrdersRoute
  '/customers/$id/': typeof CustomersIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editions': typeof EditionsRoute
  '/negatives': typeof NegativesRoute
  '/orders': typeof OrdersRoute
  '/prints': typeof PrintsRoute
  '/settings/customer-types': typeof SettingsCustomerTypesRoute
  '/settings/film-stocks': typeof SettingsFilmStocksRoute
  '/settings/manufacturers': typeof SettingsManufacturersRoute
  '/customers': typeof CustomersIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/customers/$id/notes': typeof CustomersIdNotesRoute
  '/customers/$id/orders': typeof CustomersIdOrdersRoute
  '/customers/$id': typeof CustomersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customers': typeof CustomersRouteWithChildren
  '/editions': typeof EditionsRoute
  '/negatives': typeof NegativesRoute
  '/orders': typeof OrdersRoute
  '/prints': typeof PrintsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/customers/$id': typeof CustomersIdRouteWithChildren
  '/settings/customer-types': typeof SettingsCustomerTypesRoute
  '/settings/film-stocks': typeof SettingsFilmStocksRoute
  '/settings/manufacturers': typeof SettingsManufacturersRoute
  '/customers/': typeof CustomersIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/customers/$id/notes': typeof CustomersIdNotesRoute
  '/customers/$id/orders': typeof CustomersIdOrdersRoute
  '/customers/$id/': typeof CustomersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers'
    | '/editions'
    | '/negatives'
    | '/orders'
    | '/prints'
    | '/settings'
    | '/customers/$id'
    | '/settings/customer-types'
    | '/settings/film-stocks'
    | '/settings/manufacturers'
    | '/customers/'
    | '/settings/'
    | '/customers/$id/notes'
    | '/customers/$id/orders'
    | '/customers/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/editions'
    | '/negatives'
    | '/orders'
    | '/prints'
    | '/settings/customer-types'
    | '/settings/film-stocks'
    | '/settings/manufacturers'
    | '/customers'
    | '/settings'
    | '/customers/$id/notes'
    | '/customers/$id/orders'
    | '/customers/$id'
  id:
    | '__root__'
    | '/'
    | '/customers'
    | '/editions'
    | '/negatives'
    | '/orders'
    | '/prints'
    | '/settings'
    | '/customers/$id'
    | '/settings/customer-types'
    | '/settings/film-stocks'
    | '/settings/manufacturers'
    | '/customers/'
    | '/settings/'
    | '/customers/$id/notes'
    | '/customers/$id/orders'
    | '/customers/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersRoute: typeof CustomersRouteWithChildren
  EditionsRoute: typeof EditionsRoute
  NegativesRoute: typeof NegativesRoute
  OrdersRoute: typeof OrdersRoute
  PrintsRoute: typeof PrintsRoute
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prints': {
      id: '/prints'
      path: '/prints'
      fullPath: '/prints'
      preLoaderRoute: typeof PrintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negatives': {
      id: '/negatives'
      path: '/negatives'
      fullPath: '/negatives'
      preLoaderRoute: typeof NegativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editions': {
      id: '/editions'
      path: '/editions'
      fullPath: '/editions'
      preLoaderRoute: typeof EditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/customers/': {
      id: '/customers/'
      path: '/'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/settings/manufacturers': {
      id: '/settings/manufacturers'
      path: '/manufacturers'
      fullPath: '/settings/manufacturers'
      preLoaderRoute: typeof SettingsManufacturersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/film-stocks': {
      id: '/settings/film-stocks'
      path: '/film-stocks'
      fullPath: '/settings/film-stocks'
      preLoaderRoute: typeof SettingsFilmStocksRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/customer-types': {
      id: '/settings/customer-types'
      path: '/customer-types'
      fullPath: '/settings/customer-types'
      preLoaderRoute: typeof SettingsCustomerTypesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/customers/$id/': {
      id: '/customers/$id/'
      path: '/'
      fullPath: '/customers/$id/'
      preLoaderRoute: typeof CustomersIdIndexRouteImport
      parentRoute: typeof CustomersIdRoute
    }
    '/customers/$id/orders': {
      id: '/customers/$id/orders'
      path: '/orders'
      fullPath: '/customers/$id/orders'
      preLoaderRoute: typeof CustomersIdOrdersRouteImport
      parentRoute: typeof CustomersIdRoute
    }
    '/customers/$id/notes': {
      id: '/customers/$id/notes'
      path: '/notes'
      fullPath: '/customers/$id/notes'
      preLoaderRoute: typeof CustomersIdNotesRouteImport
      parentRoute: typeof CustomersIdRoute
    }
  }
}

interface CustomersIdRouteChildren {
  CustomersIdNotesRoute: typeof CustomersIdNotesRoute
  CustomersIdOrdersRoute: typeof CustomersIdOrdersRoute
  CustomersIdIndexRoute: typeof CustomersIdIndexRoute
}

const CustomersIdRouteChildren: CustomersIdRouteChildren = {
  CustomersIdNotesRoute: CustomersIdNotesRoute,
  CustomersIdOrdersRoute: CustomersIdOrdersRoute,
  CustomersIdIndexRoute: CustomersIdIndexRoute,
}

const CustomersIdRouteWithChildren = CustomersIdRoute._addFileChildren(
  CustomersIdRouteChildren,
)

interface CustomersRouteChildren {
  CustomersIdRoute: typeof CustomersIdRouteWithChildren
  CustomersIndexRoute: typeof CustomersIndexRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersIdRoute: CustomersIdRouteWithChildren,
  CustomersIndexRoute: CustomersIndexRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

interface SettingsRouteChildren {
  SettingsCustomerTypesRoute: typeof SettingsCustomerTypesRoute
  SettingsFilmStocksRoute: typeof SettingsFilmStocksRoute
  SettingsManufacturersRoute: typeof SettingsManufacturersRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsCustomerTypesRoute: SettingsCustomerTypesRoute,
  SettingsFilmStocksRoute: SettingsFilmStocksRoute,
  SettingsManufacturersRoute: SettingsManufacturersRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersRoute: CustomersRouteWithChildren,
  EditionsRoute: EditionsRoute,
  NegativesRoute: NegativesRoute,
  OrdersRoute: OrdersRoute,
  PrintsRoute: PrintsRoute,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
