/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrintsRouteImport } from './routes/prints'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as NegativesRouteImport } from './routes/negatives'
import { Route as EditionsRouteImport } from './routes/editions'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as IndexRouteImport } from './routes/index'

const PrintsRoute = PrintsRouteImport.update({
  id: '/prints',
  path: '/prints',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const NegativesRoute = NegativesRouteImport.update({
  id: '/negatives',
  path: '/negatives',
  getParentRoute: () => rootRouteImport,
} as any)
const EditionsRoute = EditionsRouteImport.update({
  id: '/editions',
  path: '/editions',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/editions': typeof EditionsRoute
  '/negatives': typeof NegativesRoute
  '/orders': typeof OrdersRoute
  '/prints': typeof PrintsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/editions': typeof EditionsRoute
  '/negatives': typeof NegativesRoute
  '/orders': typeof OrdersRoute
  '/prints': typeof PrintsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/editions': typeof EditionsRoute
  '/negatives': typeof NegativesRoute
  '/orders': typeof OrdersRoute
  '/prints': typeof PrintsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers'
    | '/editions'
    | '/negatives'
    | '/orders'
    | '/prints'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/customers' | '/editions' | '/negatives' | '/orders' | '/prints'
  id:
    | '__root__'
    | '/'
    | '/customers'
    | '/editions'
    | '/negatives'
    | '/orders'
    | '/prints'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersRoute: typeof CustomersRoute
  EditionsRoute: typeof EditionsRoute
  NegativesRoute: typeof NegativesRoute
  OrdersRoute: typeof OrdersRoute
  PrintsRoute: typeof PrintsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/prints': {
      id: '/prints'
      path: '/prints'
      fullPath: '/prints'
      preLoaderRoute: typeof PrintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negatives': {
      id: '/negatives'
      path: '/negatives'
      fullPath: '/negatives'
      preLoaderRoute: typeof NegativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editions': {
      id: '/editions'
      path: '/editions'
      fullPath: '/editions'
      preLoaderRoute: typeof EditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersRoute: CustomersRoute,
  EditionsRoute: EditionsRoute,
  NegativesRoute: NegativesRoute,
  OrdersRoute: OrdersRoute,
  PrintsRoute: PrintsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
